DROP TABLE IF EXISTS groups, students, courses, students_courses;

CREATE TABLE groups(
GROUP_ID SERIAL PRIMARY KEY NOT NULL,
GROUP_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE students(
STUDENT_ID SERIAL NOT NULL,
GROUP_ID INT,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
PRIMARY KEY(STUDENT_ID),
FOREIGN KEY (GROUP_ID) REFERENCES groups(GROUP_ID) ON DELETE RESTRICT
);

CREATE TABLE courses(
COURSE_ID SERIAL PRIMARY KEY NOT NULL,
COURSE_NAME VARCHAR(100) NOT NULL,
COURSE_DESCRIPTION VARCHAR
);

CREATE TABLE students_courses(
STUDENT_ID INT NOT NULL,
COURSE_ID INT NOT NULL,
FOREIGN KEY (STUDENT_ID) REFERENCES students(STUDENT_ID) ON DELETE CASCADE,
FOREIGN KEY (COURSE_ID) REFERENCES courses(COURSE_ID) ON DELETE CASCADE,
PRIMARY KEY(STUDENT_ID, COURSE_ID)
);
