DROP TABLE IF EXISTS groups, students, courses;

CREATE TABLE groups(
ID INT NOT NULL,
GROUP_NAME VARCHAR(100) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE students(
ID INT NOT NULL,
GROUP_ID INT NOT NULL,
FIRST_NAME VARCHAR(100) NOT NULL,
SECOND_NAME VARCHAR(100) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE courses(
ID INT NOT NULL,
COURSE_NAME VARCHAR(100) NOT NULL,
COURSE_DESCRIPTION VARCHAR,
PRIMARY KEY(ID)
);